substitutions:
  _REGION: europe-west1
  _SERVICE: trainerpt-prod-api
  _REPO: trainerpt-api
  _PROJECT_ID: trainerpt-prod
  _IMAGE: europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

steps:
  - name: node:24
    entrypoint: bash
    args:
      - -c
      - |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm run db:generate
        pnpm run build

  - name: node:24
    entrypoint: bash
    secretEnv: ['DATABASE_URL']
    args:
      - -c
      - |
        corepack enable
        pnpm run db:update

  - name: gcr.io/buildpacks/builder
    args:
      - build
      - ${_IMAGE}
      - --path=.
      - --builder=gcr.io/buildpacks/builder:v1
      - --publish

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --allow-unauthenticated

availableSecrets:
  secretManager:
    - versionName: projects/147408060771/secrets/DATABASE_URL_PROD/versions/latest
      env: DATABASE_URL

options:
  logging: CLOUD_LOGGING_ONLY
